name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue is stale and will be closed in 7 days unless there is new activity'
        stale-pr-message: 'PR is stale and will be closed in 7 days unless there is new activity'
        stale-issue-label: 'meta/stale'
        exempt-issue-label: 'meta/stale-exempt'
        stale-pr-label: 'meta/stale'
        exempt-pr-label: 'meta/stale-exempt'
        remove-stale-when-updated: true

